### Create a note
POST http://localhost:62490/api/notes
Content-Type: application/json

{
  "title": "Local host1",
  "content": "Welcome to the Task Management API running on localhost. Use the provided endpoints to create, read, update, and delete tasks."
}

### Create a note
POST http://localhost:62490/api/notes
Content-Type: application/json

{
  "title": "Local host2",
  "content": "1Welcome to the Task Management API running on localhost. Use the provided endpoints to create, read, update, and delete tasks."
}

### Create a note
POST http://localhost:62490/api/notes
Content-Type: application/json

{
  "title": "Local host3",
  "content": "Welcome to the Task Management API running on localhost. Use the provided endpoints to create, read, update, and delete tasks."
}

### Get all notes
GET http://localhost:62490/api/notes
Accept: application/json

### Get note by its id
GET http://localhost:62490/api/notes/0e755ad3-9b95-4885-96ea-3e2234a2ef1a
Accept: application/json

### Update a note by its id
PUT http://localhost:62490/api/notes/3e3e3009-95ad-4924-8063-b20d6f887d4a
Content-Type: application/json

{
  "title": "International host",
  "content": "read, update"
}

### Delete a note by its id
DELETE http://localhost:62490/api/notes/3e3e3009-95ad-4924-8063-b20d6f887d4a
Accept: application/json