### Get account summary of savings account
GET http://localhost:60123/api/savings/summary
Accept: application/json

### Get account summary of current account
GET http://localhost:60123/api/current/summary
Accept: application/json

### Get account summary of fixed deposit account
GET http://localhost:60123/api/fixeddeposit/summary
Accept: application/json


### Post deposit for savings account
POST http://localhost:50470/api/savings/deposit
Content-Type: application/json

{
    "amount":500
}

### Post deposit for current account
POST http://localhost:60123/api/current/deposit
Content-Type: application/json

{
    "amount":600
}

### Post deposit for fixed deposit account
POST http://localhost:60123/api/fixeddeposit/deposit
Content-Type: application/json

{
    "amount":700
}


### Post withdraw for savings account
POST http://localhost:50470/api/savings/withdraw
Content-Type: application/json

{
    "amount":400
}

### Post withdraw for current account
POST http://localhost:60123/api/current/withdraw
Content-Type: application/json

{
    "amount":300
}

### Post withdraw for fixed deposit account
POST http://localhost:60123/api/fixeddeposit/withdraw
Content-Type: application/json

{
    "amount":200
}
