### Get All tasks
GET http://localhost:63956/api/tasks
Accept: application/json

### Create a task
POST http://localhost:63956/api/tasks
Content-Type: application/json

{
  "title": "Ahamed",
  "description": "task1"
}

### Update a task
PUT http://localhost:63956/api/tasks/Marshad
Accept: application/json


### Delete a task
DELETE http://localhost:63956/api/tasks/Marshad
Accept: application/json
