### Get All tasks
GET http://localhost:58866/api/tasks
Accept: application/json

### Create a task
POST http://localhost:58866/api/tasks
Content-Type: application/json

{
  "title": "Marshad",
  "description": "Nice task"
}

### Update a task
PUT localhost:58866/api/tasks/Marshad
Accept: application/json


### Delete a task
DELETE localhost:58866/api/tasks/Marshad
Accept: application/json
